services:
  mongo:
    network_mode: host
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  bot:
    network_mode: host
    build: .
    container_name: telegram-vpn-bot
    depends_on:
      - mongo
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      MONGO_URI: ${MONGO_URI}
      IP: ${IP}
      XUI_URL: ${XUI_URL}
      XUI_LOGIN: ${XUI_LOGIN}
      XUI_PASSWORD: ${XUI_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  mongo_data:

