services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PASS: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./vpn-bot/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

  3x-ui:
    image: metaligh/3x-ui:latest
    container_name: 3x-ui
    hostname: 3x-ui-panel
    network_mode: host
    environment:
      XRAY_VMESS_AEAD_FORCED: \"false\"
    volumes:
      - 3x_data:/etc/x-ui/
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    tty: true
    restart: unless-stopped

  bot:
    image: ghcr.io/teru3301/telegram-vpn:latest
    container_name: vpn-bot
    depends_on:
      - mongo
      - 3x-ui
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      MONGO_URI: ${MONGO_URI}
      IP: ${IP}
      XUI_URL: ${XUI_URL}
      XUI_LOGIN: ${XUI_LOGIN}
      XUI_PASSWORD: ${XUI_PASSWORD}
    volumes:
      - ./vpn-bot/bot:/app/data
    restart: unless-stopped

volumes:
  mongo_data:
    name: mongo_data
  mongo_config:
    name: mongo_config
  3x_data:
    name: 3x_data

