services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: tg-vpn-db
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PASS: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./mongo-init.js.tpl:/docker-entrypoint-initdb.d/mongo-init.js.tpl:ro
    entrypoint: ["/bin/sh", "-c", "envsubst < /docker-entrypoint-initdb.d/mongo-init.js.tpl > /docker-entrypoint-initdb.d/mongo-init.js && exec docker-entrypoint.sh mongod"]
    restart: unless-stopped

  bot:
    image: ghcr.io/teru3301/telegram-vpn:latest
    #network_mode: host
    container_name: vpn-bot
    depends_on:
      - mongo
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      MONGO_URI: ${MONGO_URI}
      IP: ${IP}
      XUI_URL: ${XUI_URL}
      XUI_LOGIN: ${XUI_LOGIN}
      XUI_PASSWORD: ${XUI_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  mongo_data:
    name: mongo_data
  mongo_config:
    name: mongo_config

